name: last_news
description: "Last News app is your personalized news aggregator, designed to keep you informed and connected with the world. Our app curates the latest Business, Sports, Entertainment, Health ,science and Electronics news from various global sources, providing you with a comprehensive and diverse news feed."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  persistent_bottom_nav_bar_v2: ^4.2.8
  dio: ^5.4.0
  webview_flutter: ^2.0.3
  connectivity_plus: ^5.0.2
  loading_animation_widget: ^1.2.0+4
  flutter_styled_toast: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/splash/
    - assets/svgs/
    - assets/svgs/icons/
    - assets/svgs/icons/bottom_nav_bar_icons/
    - assets/svgs/icons/home_screen_icons/
    - assets/svgs/icons/home_screen_icons/categories/
    - assets/svgs/icons/internet_connection/



  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
